insert into TYPE(id, name) values (1, 'Work');
insert into type(id, name) values (2, 'School');
insert into type(id, name) values (3, 'Home');
insert into type(id, name) values (4, 'Personal');
insert into type(id, name) values (5, 'Sport');
insert into task(id, name, done, end_Date, id_type) values (1, 'End of this project', false, null, 1);
insert into task(id, name, done, end_Date, id_type) values (2, 'Meet with Laura', true, '2021-04-08', 4);
insert into task(id, name, done, end_Date, id_type) values (3, 'Clean bathroom', true, '2021-04-16', 3);
insert into task(id, name, done, end_Date, id_type) values (4, 'Organize photo shoot', false, null, 4);
insert into task(id, name, done, end_Date, id_type) values (5, 'Upload new pictures on the side', true, '2021-03-10', 1);
insert into task(id, name, done, end_Date, id_type) values (6, 'Learn English words', false, '2021-05-01', 2);
insert into task(id, name, done, end_Date, id_type) values (7, 'Create new Api', true, '2021-02-01', 1);
insert into task(id, name, done, end_Date, id_type) values (8, 'Go to the gym', false, '2021-06-25', 5);
insert into task(id, name, done, end_Date, id_type) values (9, 'Buy new skates', false, '2021-12-01', 5);
insert into task(id, name, done, end_Date, id_type) values (10, 'Go to the skating rink', false, '2021-02-20', 5);
insert into note(id, note, id_task) values (0, 'The skating rink is not open :(', 10);
