CREATE TABLE TASK (
id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 done BOOLEAN DEFAULT FALSE,
 end_Date DATE,
 id_type INT NOT NULL
);

CREATE TABLE TYPE (
id INT AUTO_INCREMENT,
name VARCHAR(50) NOT NULL
);

CREATE TABLE NOTE (
id INT AUTO_INCREMENT PRIMARY KEY,
note VARCHAR NOT NULL,
id_task INT
);

ALTER TABLE TASK
ADD CONSTRAINT id_type
FOREIGN KEY (id_type) REFERENCES TYPE(id);

ALTER TABLE NOTE
ADD CONSTRAINT id_task
FOREIGN KEY (id_task) REFERENCES TASK(id);


